### ISSUE TITLE
Can't run via JS API

### ISSUE THREAD

**Issue by Semigradsky** [askirmas/postcss-d-ts#21]
postcss@8.2.8
postcss-d-ts@1.0.0

My code (index.js):
```js
const dts = require('postcss-d-ts')
const postcss = require('postcss')
const fs = require('fs')

fs.readFile('dx.ligt.css', (err, css) => {
  postcss([
    dts(),
  ], { from: 'dx.ligt.css', to: 'dx.out.css' })
    .process(css)
    .then(result => {
      console.log(result.css)
    })
})
```

Error:
```
dmitry@DESKTOP-Q74C34Q:~/H/_postcss/_tmp$ node index.js
/home/dmitry/H/_postcss/_tmp/node_modules/postcss/lib/processor.js:61
        throw new Error(i + ' is not a PostCSS plugin')
        ^

Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/dmitry/H/_postcss/_tmp/node_modules/postcss/lib/processor.js:61:15)
    at new Processor (/home/dmitry/H/_postcss/_tmp/node_modules/postcss/lib/processor.js:9:25)
    at postcss (/home/dmitry/H/_postcss/_tmp/node_modules/postcss/lib/postcss.js:25:10)
    at ReadFileContext.callback (/home/dmitry/H/_postcss/_tmp/index.js:6:3)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13)
```

**Comment by askirmas** [comment]
You made a wrong execution of `postcss`
https://github.com/postcss/postcss/blob/0ec123e02d88833c40b6c5bb15e297d4e09f87d4/lib/postcss.d.ts#L339-L340

`{from, to}` should be the second argument of `.process`

**Comment by Semigradsky** [comment]
Oh sorry guy, my fault...
